---
configs:
  server:
    memory: "6144"
    cpus: "4"
    ip: "192.168.56.101"
    domain: elastic.lokal
    aliases:
    - mail.elastic.lokal
    - icinga.elastic.lokal
    - grafana.elastic.lokal
  client:
    memory: "2048"
    cpus: "2"
    ip: "192.168.56.102"
    domain: client.lokal
...
