# Module: nginx
# Docs: https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-module-nginx.html

- module: nginx
  metricsets:
  - stubstatus
  enabled: true
  period: 10s

  # Nginx hosts
  hosts: ["http://127.0.0.1"]

  # Path to server status. Default server-status
  server_status_path: "server-status"

  #username: "user"
  #password: "secret"
