---

- name: install ssmtp
  apt:
    name: "{{ packages }}"
    state: latest
    dpkg_options: 'force-confnew,force-confdef'
    autoclean: yes
    autoremove: yes
    update_cache: yes
    cache_valid_time: 3600
  vars:
    packages:
    - mailutils
    - ssmtp

- name: create ssmtp.conf
  template:
    src: ssmtp.conf
    dest: /etc/ssmtp/ssmtp.conf
    owner: root
    group: mail
    mode: 0640

- block:

  - name: configure mailhog
    blockinfile:
      path: /etc/elasticsearch/elasticsearch.yml
      marker: "# {mark} activate email configuration xpack"
      content: |
        xpack.notification.email.account:
          mailhog:
            profile: mailhog
            email_defaults:
              from: <server@elastic.lokal>
            smtp:
                host: localhost
                port: {{ mailhog_smtp_port }}
  - name: start elasticsearch
    systemd:
      name: "elasticsearch"
      state: restarted
      enabled: yes

  - name: pause for one minute to allow elasticstack to come up
    pause:
      minutes: 1

  when: elasticsearch_init_trial_license|bool

...
