---
- hosts: all
  become: true
  become_method: sudo

  vars:
    required_packages:
    - git
    - tcptraceroute
    - nmap
    - jq
    - python3-pip
    required_python_packages: []
    prometheus_node_exporter_listen_ip: 0.0.0.0
    prometheus_nginx_exporter_listen_ip: 0.0.0.0
    prometheus_nginx_exporter_scrape_uri: http://127.0.0.1/server-status

  pre_tasks:
  - name: check for file custom_vars.yml
    stat:
      path: custom_vars.yml
    register: stat_custom_vars
  - name: load custom vars, if existent
    include_vars:
      file: custom_vars.yml
    when: stat_custom_vars.stat.exists

  roles:
  - andrelohmann.root_colored_prompt
  - default_tasks
  - andrelohmann.beats
  - beats_patch
  - andrelohmann.logstash
  - nginx_tasks
  - nginx_tests
  - andrelohmann.prometheus_node_exporter
  - andrelohmann.prometheus_nginx_exporter

...
