---
- andrelohmann.root_colored_prompt
- andrelohmann.zulu_openjdk
- andrelohmann.elasticstack
- andrelohmann.beats
- andrelohmann.prometheus
- andrelohmann.prometheus_node_exporter
- andrelohmann.prometheus_nginx_exporter
...
