---
roles:
- andrelohmann.root_colored_prompt
- andrelohmann.zulu_openjdk
- andrelohmann.elasticstack
- andrelohmann.beats
- andrelohmann.logstash
- andrelohmann.prometheus
- andrelohmann.prometheus_node_exporter
- andrelohmann.prometheus_nginx_exporter
- andrelohmann.grafana_oss
- andrelohmann.percona_mysql
- andrelohmann.mysql_grants
- andrelohmann.mailhog
- andrelohmann.docker
- andrelohmann.icinga2
- andrelohmann.icingabeat
# This will be necessary when Ansible 2.10 is released
#collections:
#- community.general # a dependency for the andrelohmann.grafana_oss role
#collections:
#- name: community.grafana#
#  version: 1.2.0
...
